### ISSUE TITLE
Error: AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application

### ISSUE THREAD

**Issue by ychenbioinfo** [AngellusMortis/django_microsoft_auth#244]
Hi,

I have this error when I tried to connect to Azure AD. The error showed the reply url is not correct, but I have reply/redirect url set up as "http://localhost:8000/microsoft/auth-callback" in APP settings, and I did everything else followed the instruction. Please let me if there is anything else I need to do to solve this issue. 

Thanks a lot for your help. 
Alvin

**Comment by AngellusMortis** [comment]
Not enough information to reproduce.

**Comment by filipbec** [comment]
@ychenbioinfo: I had the same issue. The library uses `current_site.domain` to compose `redirect_uri` parameter, so you need to set _Domain name_ for the site as `localhost:8000`. Authentication request will then have correct `redirect_uri` value. I was also confused what _hostname + post_ means in the documentation and that's why I defined _Domain name_ just as `localhost`.

@AngellusMortis: I opened #252 which probably resolves the issue 🙂
