### ISSUE TITLE
pip incompatibility

### ISSUE THREAD

**Issue by yeago** [AngellusMortis/django_microsoft_auth#402]
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-gb2iu7r4/django-microsoft-auth/setup.py", line 39, in <module>
        requirements[req] = [str(req.req) for req in reqs]
      File "/tmp/pip-install-gb2iu7r4/django-microsoft-auth/setup.py", line 39, in <listcomp>
        requirements[req] = [str(req.req) for req in reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'

**Comment by yeago** [comment]
May have something to do with the release of pip 4/28/2020

**Comment by clreinki** [comment]
Wow you beat me to it.  I just redeployed my Django app to Azure and it failed to deploy with this same error :(

**Comment by nabazm** [comment]
same here, upgraded to 2.0.2 also not luck

**Comment by yeago** [comment]
@clreinki yes i saw your post in the microsoft forum this morning but didn't have an account to harass you there :)

**Comment by yasht-21** [comment]
Hey, Did anybody was able to find a fix for it? Thanks in Advance :)

**Comment by clreinki** [comment]
@yasht-21 I got it to work by taking a figurative hammer to it...
I [forked the project](https://github.com/clreinki/django_microsoft_auth) and simply removed all requirements in the setup.py.  Terrible I know but since I already had the dependencies added to my requirements.txt it was fine.  I'm not sure how to actually fix it as I'm unfamiliar with the setup.py process but I'm hoping someone more knowledgeable than me can eventually submit a patch to truly fix it.

**Comment by yeago** [comment]
or, like i said, peg to 20.0.2 pip its just using some deprecated feature
and i am sure a fix will eventually come if it doesn't exist already in the
forks somewhere

**Comment by clreinki** [comment]
@yasht-21 How do you peg to 20.0.2?

**Comment by AngellusMortis** [comment]
You can either do `pip install pip<20` or make a PR to fix the issue and make `setup.py` to not use pip to parse requirements. Here is an example: https://github.com/AngellusMortis/sxm-player/blob/master/setup.py
