### ISSUE TITLE
Flake8 Failing

### ISSUE THREAD

**Issue by Casey-Kiewit** [AngellusMortis/django_microsoft_auth#494]
[The contribution guide calls for Flake8 to be passing for any new changes](https://github.com/AngellusMortis/django_microsoft_auth/blob/master/CONTRIBUTING.rst#get-started), but the existing codebase raises a significant number of Flake8 warnings. Once these are addressed, it'd be nice to have a workflow in-place to enforce this guideline.

**Comment by Casey-Kiewit** [comment]
I'm going to work on addressing this and putting together a workflow.

**Comment by AngellusMortis** [comment]
Flake8 is _running_ in CI and it is passing. But it only runs on the default Python and uses pyproject-flake8 so the config can exist in the same pyproject.toml. The maintainer of flake8 refuses to implement pyproject.toml support. It is a lot of drama and I feel like most of it is because he wants to force people to his other project, pre-commit, that he makes money off of.

https://github.com/AngellusMortis/django_microsoft_auth/blob/master/.github/workflows/ci.yml#L38
https://github.com/AngellusMortis/django_microsoft_auth/actions/runs/3550096405/jobs/5963165016

**Comment by Casey-Kiewit** [comment]
That's good to know. Would it be possible to clarify the recommended way to run Flake8, since the way recommended in the existing documentation results in a lot of unintended warnings?

**Comment by Casey-Kiewit** [comment]
Closing this since it's a duplicate of https://github.com/AngellusMortis/django_microsoft_auth/issues/487.
